name: Blob storage website CI

on:
  push:
    branches:
      - master
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Vite Compilation Steps
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
    
    #Azure Uploading
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name bedoyasanstorage  --auth-mode key -d '$web' -s ./dist
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
             az cdn endpoint purge --content-paths  "/*" --profile-name "bedoyasanfdcdn" --name "bedoyasan" --resource-group "BedoyaSanRG"
